language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.prod -t sample:prod .

script:
  - docker run -it --rm -p 1337:80 sample:prod npm run test

after_success:
  - docker build -f Dockerfile.prod -t sample:prod .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push indreklasn/my-react-docker-app
