language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t podcast-app_sample-prod -f Dockerfile.dev .

script:
  - docker run -e CI=true podcast-app_sample-prod npm run test

after_success:
  - docker build -t podcast-app_sample-prod .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push podcast-app_sample-prod
